[package]
name = "ferromark_parser"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "High-performance Markdown parser for Ferromark"

[lints]
workspace = true

[dependencies]
ferromark_allocator = { workspace = true }
ferromark_ast = { workspace = true }
thiserror = { workspace = true }
memchr = { workspace = true }
rustc-hash = { workspace = true }
compact_str = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
insta = { workspace = true }
ferromark_renderer = { workspace = true }

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "prepass"
harness = false

[[bench]]
name = "tables"
harness = false

[[bench]]
name = "table_pipes"
harness = false
