[package]
name="ferromark"
version="0.9.0"
edition="2024"
[workspace]
[lib]
path="src/lib.rs"
[features]
default=[]
mdx=[]
profiling=[]
[dependencies]
memchr="=2.8.3"
smallvec="=1.15.2"
html-escape={version="=0.2.14",default-features=false}
rustc-hash="=2.1.3"
unicode-ident="=1.0.24"
