// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("guide/benchmarks", "routes/guide/benchmarks.mdx"),
  route("guide/features", "routes/guide/features.mdx"),
  route("guide/getting-started", "routes/guide/getting-started.mdx"),
  route("guide/mdx-examples", "routes/guide/mdx-examples.mdx"),
  route("guide/quick-start", "routes/guide/quick-start.mdx"),
] satisfies RouteConfig
