// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("guide/architecture", "routes/guide/architecture.mdx"),
  route("guide/benchmark-explorer", "routes/guide/benchmark-explorer.mdx"),
  route("guide/benchmarks", "routes/guide/benchmarks.mdx"),
  route("guide/cli", "routes/guide/cli.mdx"),
  route("guide/configuration", "routes/guide/configuration.mdx"),
  route("guide/correctness", "routes/guide/correctness.mdx"),
  route("guide/feature-comparison", "routes/guide/feature-comparison.mdx"),
  route("guide/features", "routes/guide/features.mdx"),
  route("guide/getting-started", "routes/guide/getting-started.mdx"),
  route("guide/mdx", "routes/guide/mdx.mdx"),
  route("guide/mdx-examples", "routes/guide/mdx-examples.mdx"),
  route("guide/pipelines", "routes/guide/pipelines.mdx"),
  route("guide/quick-start", "routes/guide/quick-start.mdx"),
  route("guide/rendering", "routes/guide/rendering.mdx"),
  route("guide/workflow-benchmarks", "routes/guide/workflow-benchmarks.mdx"),
  route("node/configuration", "routes/node/configuration.mdx"),
  route("node/deployment", "routes/node/deployment.mdx"),
  route("node/getting-started", "routes/node/getting-started.mdx"),
  route("node/highlighting", "routes/node/highlighting.mdx"),
  route("node/pipelines", "routes/node/pipelines.mdx"),
  route("rust/configuration", "routes/rust/configuration.mdx"),
  route("rust/getting-started", "routes/rust/getting-started.mdx"),
  route("rust/highlighting", "routes/rust/highlighting.mdx"),
  route("rust/mdx", "routes/rust/mdx.mdx"),
  route("rust/mdx-examples", "routes/rust/mdx-examples.mdx"),
  route("rust/pipelines", "routes/rust/pipelines.mdx"),
  route("rust/transforms", "routes/rust/transforms.mdx"),
] satisfies RouteConfig
