#!/usr/bin/env python3
"""Stage geomeans per run, per-document matrices and group breakdowns: numbers.py [out.md]

Reads results/ of the report this harness belongs to and writes NUMBERS.md next to it by default.
"""
import json
import math
import re
import sys
from collections import defaultdict
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else REPORT / "NUMBERS.md"
MODES = ("fresh", "reuse", "parse", "render")
LABELS = {
    "aa": "A/A control (baseline against itself)",
    "trim": "`trim` #414 ASCII-only block trimming",
    "prescan": "`prescan` #413 fused root scan, first commit",
    "prescan2": "`prescan2` #413 with the overlapping final vector",
    "tagfilter": "`tagfilter` #411 tag filter first-byte gate",
    "autolink": "`autolink` #415 pre-flight inside the marker scan",
    "stack1": "`stack1` #413 on `cb352020` + #414",
    "stack2": "`stack2` #411 on `cb352020` + #414 + #413",
    "total": "`total` #414 + #413 + #411 together on `cb352020`",
}
SECTIONS = [
    ("Screens: 20 documents and 16 diagnostics, 3 rounds × 3 pairs, baseline `cb352020`",
     ["aa-screen", "trim-screen", "prescan-screen", "prescan2-screen", "tagfilter-screen", "autolink-screen"]),
    ("Broad confirmations: 57 documents, 3 rounds × 5 pairs, baseline `cb352020`",
     ["trim-broad", "prescan-broad", "prescan2-broad", "tagfilter-broad", "autolink-broad"]),
    ("Recheck: 4 documents, 3 rounds × 7 pairs, baseline `cb352020`",
     ["aa-recheck", "tagfilter-recheck"]),
    ("Stacked re-screens: 36 cases, 3 rounds × 3 pairs, each on the state that holds the previous changes",
     ["stack1-screen", "stack2-screen"]),
    ("Cumulative: 57 documents, 3 rounds × 5 pairs, `cb352020` against all three Rust changes",
     ["total-broad"]),
]


def geomean(values):
    return math.exp(sum(math.log(v) for v in values) / len(values))


def load(run):
    directory = REPORT / "results" / run
    return json.loads((directory / "summary.json").read_text()), json.loads((directory / "grouped.json").read_text())


def label(run):
    return LABELS[run.rsplit("-", 1)[0]]


lines = [
    "# Numbers", "",
    "Ratios are baseline time over candidate time (median of the paired windows); "
    "**higher is faster, below 1.000 the candidate is slower**.",
    "Every screen, broad and recheck row uses `cb352020` as its baseline and one branch on its own, so those rows are "
    "independent, not cumulative. The stacked rows use the state that already holds the previous changes as their "
    "baseline. Generated by `harness/numbers.py` from `results/`.", "",
]
for title, runs in SECTIONS:
    lines += [f"## {title}", "",
              "| Run | fresh | reuse | parse | render | fresh rounds | reuse rounds | parse rounds | render rounds |",
              "| --- | ---: | ---: | ---: | ---: | --- | --- | --- | --- |"]
    counts = []
    for run in runs:
        summary, grouped = load(run)
        g = grouped["all"]
        lines.append(f"| {label(run)} | " + " | ".join(f"{g[m]['geometric_mean']:.4f}" for m in MODES) + " | "
                     + " | ".join(" / ".join(f"{x:.3f}" for x in g[m]["round_geometric_means"]) for m in MODES) + " |")
        row = []
        for m in MODES:
            mine = [r for r in summary if r["mode"] == m]
            up = sum(r["baseline_over_candidate_median"] > 1.0 for r in mine)
            low = sum(r["baseline_over_candidate_median"] < 0.970 for r in mine)
            row.append(f"{up}/{len(mine)} ({low})")
        counts.append(f"| {label(run)} | " + " | ".join(row) + " |")
    lines += ["", "Cases faster than the baseline, and in parentheses cases below 0.970:", "",
              "| Run | fresh | reuse | parse | render |", "| --- | ---: | ---: | ---: | ---: |"] + counts + [""]

# Per-document matrices.
for kind, runs, modes in (
    ("screen", ["aa-screen", "trim-screen", "prescan-screen", "prescan2-screen", "tagfilter-screen", "autolink-screen",
                "stack1-screen", "stack2-screen"], ("fresh", "parse", "render")),
    ("broad", ["trim-broad", "prescan-broad", "prescan2-broad", "tagfilter-broad", "autolink-broad", "total-broad"],
     ("fresh", "reuse", "parse", "render")),
):
    per_case = defaultdict(dict)
    for run in runs:
        for row in load(run)[0]:
            per_case[row["mode"], row["case"]][run] = row["baseline_over_candidate_median"]
    names = [r.rsplit("-", 1)[0] for r in runs]
    for mode in modes:
        lines += [f"## Per-document {mode} ratios, {kind}", "",
                  "| Document | " + " | ".join(names) + " |", "| --- | " + " | ".join("---:" for _ in runs) + " |"]
        for case in sorted({c for (m, c) in per_case if m == mode}):
            values = per_case[mode, case]
            lines.append(f"| `{case}` | " + " | ".join(f"{values[r]:.3f}" if r in values else "—" for r in runs) + " |")
        lines.append("")
    if kind == "screen":
        lines += ["The `stack1` and `stack2` columns have their own baselines (see above), not `cb352020`.", ""]

# Group breakdown of the broad runs.
cases = json.loads((REPORT / "results" / "cases.json").read_text())["cases"]
runs = ["trim-broad", "prescan2-broad", "tagfilter-broad", "autolink-broad", "total-broad"]
for mode in ("parse", "render"):
    groups = defaultdict(lambda: defaultdict(list))
    for run in runs:
        for row in load(run)[0]:
            if row["mode"] != mode:
                continue
            meta = cases[row["case"]]
            groups[f"profile `{meta['profile']}`"][run].append(row["baseline_over_candidate_median"])
            groups[f"category `{meta['category']}`"][run].append(row["baseline_over_candidate_median"])
    lines += [f"## Broad {mode} geomeans by profile and category", "",
              "| Group | Documents | " + " | ".join(r.rsplit("-", 1)[0] for r in runs) + " |",
              "| --- | ---: | " + " | ".join("---:" for _ in runs) + " |"]
    for group in sorted(groups, key=lambda g: (not g.startswith("profile"), g)):
        values = groups[group]
        lines.append(f"| {group} | {len(values[runs[0]])} | " + " | ".join(f"{geomean(values[r]):.3f}" for r in runs) + " |")
    lines.append("")

# Node-level comparison for #412.
node = (REPORT / "results" / "node-412.txt").read_text()
lines += ["## Node level: #412, reused renderer output buffer", "",
          "57 broad documents at equal byte volume per document, addons built from `cb352020` (A) and the #412 branch "
          "(B) as local `release-node` builds without PGO, alternated in separate child processes over 10 rounds with "
          "the order swapped every round; each child reports the median of 5 sweeps per lane. Ratio is A time over "
          "B time, so above 1.000 the branch is faster. Raw output: `results/node-412.txt`.", "",
          "| Round | reuse A ms | reuse B ms | reuse ratio | one-shot A ms | one-shot B ms | one-shot ratio |",
          "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |"]
for match in re.finditer(r"round (\d+): A (\{.*?\}) B (\{.*?\})", node):
    a, b = json.loads(match.group(2)), json.loads(match.group(3))
    lines.append(f"| {match.group(1)} | {a['reuse']:.2f} | {b['reuse']:.2f} | {a['reuse'] / b['reuse']:.3f} | "
                 f"{a['oneshot']:.2f} | {b['oneshot']:.2f} | {a['oneshot'] / b['oneshot']:.3f} |")
medians = dict(re.findall(r"^(\w+): median A/B ([\d.]+)", node, re.M))
lines += ["", f"Median ratio: reused `Renderer.toHtml` **{medians['reuse']}**, one-shot `toHtml` {medians['oneshot']} "
          "(code unchanged by #412, so it serves as the control). `node-bench.mjs` reports the upper median, the sixth "
          "of the ten sorted round ratios.", ""]

OUT.write_text("\n".join(lines))
print("wrote", OUT)
