#!/usr/bin/env python3
"""Per-case markdown tables for every run of the round: tables.py [out.md]

Reads results/ of the report this harness belongs to and writes TABLES.md next to it by default.
Case metadata (category, profile, bytes) comes from results/cases.json, which was taken from the
paired corpus (make_corpus.py --include-scanner-diagnostics; its SHA-256 is in every run.json).
"""
import json
import sys
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else REPORT / "TABLES.md"
RUNS = [
    ("aa-screen", "A/A control, screen"),
    ("trim-screen", "`trim` #414 ASCII-only block trimming, screen"),
    ("prescan-screen", "`prescan` #413 fused root scan, first commit, screen"),
    ("prescan2-screen", "`prescan2` #413 with the overlapping final vector, screen"),
    ("tagfilter-screen", "`tagfilter` #411 tag filter first-byte gate, screen"),
    ("autolink-screen", "`autolink` #415 pre-flight inside the marker scan, screen"),
    ("trim-broad", "`trim` #414, broad"),
    ("prescan-broad", "`prescan` #413 first commit, broad"),
    ("prescan2-broad", "`prescan2` #413 revised, broad"),
    ("tagfilter-broad", "`tagfilter` #411, broad"),
    ("autolink-broad", "`autolink` #415, broad"),
    ("aa-recheck", "A/A control, recheck of four documents"),
    ("tagfilter-recheck", "`tagfilter` #411, recheck of four documents"),
    ("stack1-screen", "`stack1`: #413 on `cb352020` + #414, screen"),
    ("stack2-screen", "`stack2`: #411 on `cb352020` + #414 + #413, screen"),
    ("total-broad", "`total`: #414 + #413 + #411 together on `cb352020`, broad"),
]
cases = json.loads((REPORT / "results" / "cases.json").read_text())["cases"]
lines = ["# Per-case tables", "",
         "Ratios are baseline time over candidate time (median of the paired windows); higher is faster.",
         "`Rounds` lists the per-round medians. Baseline time is the median nanoseconds per document.",
         "Generated by `harness/tables.py` from `results/`.", ""]
for name, heading in RUNS:
    rows = json.loads((REPORT / "results" / name / "summary.json").read_text())
    lines += [f"## {heading}", ""]
    for mode in ("fresh", "reuse", "parse", "render"):
        selected = sorted((r for r in rows if r["mode"] == mode), key=lambda r: r["baseline_over_candidate_median"])
        if not selected:
            continue
        lines += [f"### {mode}", "",
                  "| Case | Category | Profile | Bytes | Ratio | Min | Max | Rounds | Baseline ns/doc |",
                  "| --- | --- | --- | ---: | ---: | ---: | ---: | --- | ---: |"]
        for r in selected:
            c = cases[r["case"]]
            lines.append(f"| `{r['case']}` | {c['category']} | {c['profile']} | {c['byte_count']} | "
                         f"{r['baseline_over_candidate_median']:.3f} | {r['baseline_over_candidate_min']:.3f} | "
                         f"{r['baseline_over_candidate_max']:.3f} | {' / '.join(f'{x:.3f}' for x in r['round_medians'])} | "
                         f"{r['baseline_ns_per_document']:,.0f} |")
        lines.append("")
OUT.write_text("\n".join(lines))
print("wrote", OUT, sum(1 for line in lines if line.startswith("| `")), "rows")
