use crate::allocator::{Allocator, Vec};
use crate::ast::{Node, Span};

use super::super::line_scan::{line_end, line_terminator_end};

pub(super) struct JsxChildSource<'a> {
    pub source: &'a str,
    pub offsets: Option<Vec<'a, u32>>,
}

pub(super) fn normalize_indentation<'a>(
    allocator: &'a Allocator,
    source: &'a str,
) -> JsxChildSource<'a> {
    let common_indent = common_line_indent(source);
    if common_indent == 0 {
        return JsxChildSource {
            source,
            offsets: None,
        };
    }

    let bytes = source.as_bytes();
    let mut normalized = crate::allocator::String::with_capacity_in(source.len(), allocator.bump());
    let mut offsets: Vec<'a, u32> = allocator.new_vec();
    let mut line_start = 0usize;

    while line_start < bytes.len() {
        let (line_end, next_line) = line_bounds(bytes, line_start);
        let content_start = strip_indent_columns(bytes, line_start, line_end, common_indent);
        push_mapped_slice(
            source,
            content_start,
            next_line,
            &mut normalized,
            &mut offsets,
        );
        line_start = next_line;
    }

    if offsets.is_empty() {
        offsets.push(0);
    }

    JsxChildSource {
        source: normalized.into_bump_str(),
        offsets: Some(offsets),
    }
}

/// JSX normalization maps generated byte boundaries back to its original
/// child source. The shared traversal owns all AST node and attribute shapes.
struct JsxSourceMap<'s> {
    source_offset: u32,
    offsets: &'s [u32],
}

impl super::super::spans::SpanMap for JsxSourceMap<'_> {
    fn map_span(&self, span: Span) -> Span {
        Span::new(
            self.source_offset + boundary_offset(span.start as usize, self.offsets),
            self.source_offset + boundary_offset(span.end as usize, self.offsets),
        )
    }
}

pub(super) fn remap_node_spans(node: &mut Node<'_>, source_offset: u32, offsets: &[u32]) {
    super::super::Parser::remap_node_spans(
        node,
        &JsxSourceMap {
            source_offset,
            offsets,
        },
    );
}

fn common_line_indent(source: &str) -> usize {
    let bytes = source.as_bytes();
    let mut line_start = 0usize;
    let mut common = None;

    while line_start < bytes.len() {
        let (line_end, next_line) = line_bounds(bytes, line_start);
        if let Some(first_non_ws) = first_non_whitespace(bytes, line_start, line_end) {
            let indent = indent_width(bytes, line_start, first_non_ws);
            common = Some(common.map_or(indent, |value: usize| value.min(indent)));
            if common == Some(0) {
                break;
            }
        }
        line_start = next_line;
    }

    common.unwrap_or(0)
}

fn line_bounds(bytes: &[u8], line_start: usize) -> (usize, usize) {
    // One terminator search answers both questions: the second is the
    // width of the terminator that the first one stopped on.
    let end = line_end(bytes, line_start);
    (end, line_terminator_end(bytes, end))
}

fn first_non_whitespace(bytes: &[u8], line_start: usize, line_end: usize) -> Option<usize> {
    let mut cursor = line_start;
    while cursor < line_end && matches!(bytes[cursor], b' ' | b'\t') {
        cursor += 1;
    }
    (cursor < line_end).then_some(cursor)
}

fn indent_width(bytes: &[u8], line_start: usize, first_non_ws: usize) -> usize {
    let mut columns = 0usize;
    for &byte in &bytes[line_start..first_non_ws] {
        match byte {
            b'\t' => columns = (columns / 4 + 1) * 4,
            _ => columns += 1,
        }
    }
    columns
}

fn strip_indent_columns(bytes: &[u8], line_start: usize, line_end: usize, columns: usize) -> usize {
    let mut cursor = line_start;
    let mut column = 0usize;
    while cursor < line_end && column < columns {
        match bytes[cursor] {
            b' ' => {
                column += 1;
                cursor += 1;
            }
            b'\t' => {
                column = (column / 4 + 1) * 4;
                cursor += 1;
            }
            _ => break,
        }
    }
    cursor
}

fn push_mapped_slice(
    source: &str,
    start: usize,
    end: usize,
    normalized: &mut crate::allocator::String<'_>,
    offsets: &mut Vec<'_, u32>,
) {
    if start >= end {
        if offsets.is_empty() {
            offsets.push(start as u32);
        }
        return;
    }

    if offsets.is_empty() {
        offsets.push(start as u32);
    }
    normalized.push_str(&source[start..end]);

    let mut offset = start + 1;
    while offsets.len() < normalized.len() + 1 {
        offsets.push(offset.min(end) as u32);
        offset += 1;
    }
}

fn boundary_offset(index: usize, offsets: &[u32]) -> u32 {
    offsets
        .get(index)
        .copied()
        .unwrap_or_else(|| offsets.last().copied().unwrap_or_default())
}
