//! CommonMark source normalization before any syntax or reference parsing.
use crate::allocator::{Allocator, Vec};
use crate::ast::Span;

use super::spans::SpanMap;

/// One generated byte offset per replacement, not one entry per source byte.
/// Only the root parser owns this map; nested parsers already see normalized
/// source and remap their stripped-source spans before this final mapping.
pub(super) struct NormalizedSourceMap<'a> {
    replacements: Vec<'a, u32>,
    source_start: u32,
    original_len: u32,
}

pub(super) fn normalize<'a>(
    allocator: &'a Allocator,
    source: &'a str,
    body_start: usize,
) -> (&'a str, Option<&'a NormalizedSourceMap<'a>>) {
    let bytes = source.as_bytes();
    // Only a BOM at the original document start is an encoding marker.
    // A BOM after an extracted metadata block is ordinary body content.
    let source_start = if body_start > 0 {
        body_start
    } else {
        usize::from(bytes.starts_with(b"\xEF\xBB\xBF")) * 3
    };
    let first_nul = memchr::memchr(0, &bytes[source_start..]).map(|offset| source_start + offset);
    let Some(first) = first_nul else {
        if source_start == 0 {
            // Keep ordinary Markdown borrowed, with no map or string allocation.
            return (source, None);
        }
        let map = allocator.alloc(NormalizedSourceMap {
            replacements: allocator.new_vec(),
            source_start: source_start as u32,
            original_len: source.len() as u32,
        });
        // Prefix-only normalization borrows the body without a generated copy.
        return (&source[source_start..], Some(map));
    };
    let mut normalized = allocator.new_string();
    normalized.reserve(source.len() - source_start + 2);
    normalized.push_str(&source[source_start..first]);
    let mut replacements = allocator.new_vec();
    let mut start = first;
    for relative in memchr::memchr_iter(0, &bytes[first..]) {
        let offset = first + relative;
        normalized.push_str(&source[start..offset]);
        replacements.push(normalized.len() as u32);
        normalized.push('\u{fffd}');
        start = offset + 1;
    }
    normalized.push_str(&source[start..]);
    let map = allocator.alloc(NormalizedSourceMap {
        replacements,
        source_start: source_start as u32,
        original_len: source.len() as u32,
    });
    (normalized.into_bump_str(), Some(map))
}

impl NormalizedSourceMap<'_> {
    fn boundary(&self, offset: u32) -> u32 {
        let count = self
            .replacements
            .partition_point(|&start| start + 3 <= offset);
        // AST boundaries normally cannot split U+FFFD. Clamp defensively if an
        // error points inside it, so returned offsets remain source boundaries.
        let offset = self
            .replacements
            .get(count)
            .copied()
            .filter(|&start| start < offset)
            .unwrap_or(offset);
        offset - 2 * count as u32 + self.source_start
    }
}

impl SpanMap for NormalizedSourceMap<'_> {
    fn map_span(&self, span: Span) -> Span {
        let start = self.boundary(span.start);
        let end = if span.start == span.end {
            start
        } else {
            self.boundary(span.end)
        };
        Span::new(start, end)
    }
    fn map_document_span(&self, _span: Span) -> Span {
        Span::new(0, self.original_len)
    }
}
