//! CommonMark source normalization before any syntax or reference parsing.
//!
//! Finding NUL is a pass over the whole body. For the root document that runs
//! the definition pre-pass, the same pass also finds the pre-pass's first
//! `]:` (see [`root_scan`](super::root_scan)); every other parser keeps the
//! plain `memchr`.
use crate::allocator::{Allocator, Vec};
use crate::ast::Span;

use super::root_scan::{self, DefinitionCloser, RootScan};
use super::spans::SpanMap;

/// One generated byte offset per replacement, not one entry per source byte.
/// Only the root parser owns this map; nested parsers already see normalized
/// source and remap their stripped-source spans before this final mapping.
pub(super) struct NormalizedSourceMap<'a> {
    replacements: Vec<'a, u32>,
    source_start: u32,
    original_len: u32,
}

/// Strips a leading BOM (or the metadata block ending at `body_start`) and
/// replaces every NUL with U+FFFD.
///
/// With `find_closer`, the same pass also finds the first `]:` of the
/// normalized source for the definition pre-pass. It is only answered for a
/// body without NUL: replacing one moves every later offset, so a body that
/// holds one reports [`DefinitionCloser::Unscanned`], as does every call
/// without `find_closer`.
pub(super) fn normalize<'a>(
    allocator: &'a Allocator,
    source: &'a str,
    body_start: usize,
    find_closer: bool,
) -> (
    &'a str,
    Option<&'a NormalizedSourceMap<'a>>,
    DefinitionCloser,
) {
    let bytes = source.as_bytes();
    // Only a BOM at the original document start is an encoding marker.
    // A BOM after an extracted metadata block is ordinary body content.
    let source_start = if body_start > 0 {
        body_start
    } else {
        usize::from(bytes.starts_with(b"\xEF\xBB\xBF")) * 3
    };
    let body = &bytes[source_start..];
    let (first_nul, closer) = if find_closer {
        match root_scan::scan(body) {
            RootScan::Nul(offset) => (Some(offset), DefinitionCloser::Unscanned),
            RootScan::Clean { first_closer } => (
                None,
                first_closer.map_or(DefinitionCloser::Absent, DefinitionCloser::At),
            ),
        }
    } else {
        (memchr::memchr(0, body), DefinitionCloser::Unscanned)
    };
    let (normalized, map) = replace_nul(
        allocator,
        source,
        source_start,
        first_nul.map(|offset| source_start + offset),
    );
    (normalized, map, closer)
}

/// The normalized source and its map, given where the body starts and where
/// its first NUL is.
fn replace_nul<'a>(
    allocator: &'a Allocator,
    source: &'a str,
    source_start: usize,
    first_nul: Option<usize>,
) -> (&'a str, Option<&'a NormalizedSourceMap<'a>>) {
    let bytes = source.as_bytes();
    let Some(first) = first_nul else {
        if source_start == 0 {
            // Keep ordinary Markdown borrowed, with no map or string allocation.
            return (source, None);
        }
        let map = allocator.alloc(NormalizedSourceMap {
            replacements: allocator.new_vec(),
            source_start: source_start as u32,
            original_len: source.len() as u32,
        });
        // Prefix-only normalization borrows the body without a generated copy.
        return (&source[source_start..], Some(map));
    };
    let mut normalized = allocator.new_string();
    normalized.reserve(source.len() - source_start + 2);
    normalized.push_str(&source[source_start..first]);
    let mut replacements = allocator.new_vec();
    let mut start = first;
    for relative in memchr::memchr_iter(0, &bytes[first..]) {
        let offset = first + relative;
        normalized.push_str(&source[start..offset]);
        replacements.push(normalized.len() as u32);
        normalized.push('\u{fffd}');
        start = offset + 1;
    }
    normalized.push_str(&source[start..]);
    let map = allocator.alloc(NormalizedSourceMap {
        replacements,
        source_start: source_start as u32,
        original_len: source.len() as u32,
    });
    (normalized.into_bump_str(), Some(map))
}

impl NormalizedSourceMap<'_> {
    fn boundary(&self, offset: u32) -> u32 {
        let count = self
            .replacements
            .partition_point(|&start| start + 3 <= offset);
        // AST boundaries normally cannot split U+FFFD. Clamp defensively if an
        // error points inside it, so returned offsets remain source boundaries.
        let offset = self
            .replacements
            .get(count)
            .copied()
            .filter(|&start| start < offset)
            .unwrap_or(offset);
        offset - 2 * count as u32 + self.source_start
    }
}

impl SpanMap for NormalizedSourceMap<'_> {
    fn map_span(&self, span: Span) -> Span {
        let start = self.boundary(span.start);
        let end = if span.start == span.end {
            start
        } else {
            self.boundary(span.end)
        };
        Span::new(start, end)
    }
    fn map_document_span(&self, _span: Span) -> Span {
        Span::new(0, self.original_len)
    }
}

#[cfg(test)]
mod tests {
    // Owned strings keep the test oracle independent of production storage.
    #![allow(
        clippy::disallowed_macros,
        clippy::disallowed_methods,
        clippy::disallowed_types
    )]

    use std::path::Path;

    use crate::allocator::Allocator;

    use super::{DefinitionCloser, NormalizedSourceMap, normalize};

    /// Metadata that holds both needles, which the body scan must not see.
    const FRONT_MATTER: &str = "---\ntitle: \"[a]: /x \0\"\n---\n";

    fn map_fields(map: Option<&NormalizedSourceMap<'_>>) -> Option<(Vec<u32>, u32, u32)> {
        map.map(|map| {
            (
                map.replacements.to_vec(),
                map.source_start,
                map.original_len,
            )
        })
    }

    /// The root normalization has to produce the plain one's source and map,
    /// and hand the pre-pass the `]:` its own search finds in that source.
    #[track_caller]
    fn check(source: &str, body_start: usize, label: &str) {
        let allocator = Allocator::new();
        let (plain, plain_map, unscanned) = normalize(&allocator, source, body_start, false);
        assert_eq!(unscanned, DefinitionCloser::Unscanned, "{label}");
        let (root, root_map, closer) = normalize(&allocator, source, body_start, true);
        assert_eq!(root, plain, "{label}");
        assert_eq!(map_fields(root_map), map_fields(plain_map), "{label}");
        if plain_map.is_some_and(|map| !map.replacements.is_empty()) {
            // A NUL was replaced, so the pre-pass searches the rewritten body.
            assert_eq!(closer, DefinitionCloser::Unscanned, "{label}");
        } else {
            let expected = memchr::memmem::find(plain.as_bytes(), b"]:")
                .map_or(DefinitionCloser::Absent, DefinitionCloser::At);
            assert_eq!(closer, expected, "{label}");
        }
    }

    /// `markdown` as a whole document, behind a BOM, behind front matter, and
    /// with a NUL at its start, middle and end.
    fn check_variants(markdown: &str, label: &str) {
        check(markdown, 0, label);
        check(&format!("\u{feff}{markdown}"), 0, label);
        check(
            &format!("{FRONT_MATTER}{markdown}"),
            FRONT_MATTER.len(),
            label,
        );
        let middle = (0..=markdown.len() / 2)
            .rev()
            .find(|&at| markdown.is_char_boundary(at))
            .unwrap_or(0);
        for at in [0, middle, markdown.len()] {
            let with_nul = format!("{}\0{}", &markdown[..at], &markdown[at..]);
            check(&with_nul, 0, label);
            check(&format!("\u{feff}{with_nul}"), 0, label);
            check(
                &format!("{FRONT_MATTER}{with_nul}"),
                FRONT_MATTER.len(),
                label,
            );
        }
    }

    #[test]
    fn short_shapes() {
        for markdown in [
            "",
            "]:",
            "[a]: /url",
            "\u{feff}",
            "\u{feff}]:",
            "]\u{feff}:",
            "text ]",
            ": text",
            "[link](/url) and ]: later",
            "é]:🙂",
        ] {
            check_variants(markdown, markdown);
        }
    }

    #[test]
    fn every_prefix_of_short_documents() {
        // Every body length up to a few vectors, so the root scan ends on each
        // tail length, through the same variants as the fixtures.
        for document in [
            "Does this also apply when the connection is already open? I can still \
             reproduce the original behavior after refreshing the page, but only on \
             the first request.\n",
            "Thanks, see [the docs][ref] and `a]:b`.\n\n[ref]: /target \"Title\"\n\n\
             [^n]: note é🙂\n\nMore prose after the definitions, [ref] again.\n",
        ] {
            for end in (0..=document.len()).filter(|&end| document.is_char_boundary(end)) {
                check_variants(&document[..end], &format!("prefix {end} of {document:?}"));
            }
        }
    }

    #[test]
    fn specification_fixtures() {
        const FENCE: &str = "````````````````````````````````";
        let root = Path::new(env!("CARGO_MANIFEST_DIR"));
        let mut checked = 0usize;
        for fixture in [
            "tests/spec_fixtures/commonmark-0.31.2-spec.txt",
            "tests/spec_fixtures/gfm-extensions-spec.txt",
        ] {
            let path = root.join(fixture);
            let text = std::fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
            check_variants(&text, fixture);
            // Every example and every stretch of prose between two.
            for (index, piece) in text.split(FENCE).enumerate() {
                check_variants(piece, &format!("{fixture} piece {index}"));
                checked += 1;
            }
        }
        assert!(
            checked > 1_000,
            "expected the full spec suite, got {checked}"
        );
    }

    #[test]
    fn measurement_corpora() {
        for (relative, expected_cases) in [
            ("docs/reports/2026-09-14-broad-markdown/corpus.json.gz", 57),
            ("docs/reports/2026-09-15-release-native/corpus.json.gz", 57),
            ("docs/reports/2026-09-16-arm-round-3/corpus.json.gz", 207),
        ] {
            let path = Path::new(env!("CARGO_MANIFEST_DIR")).join(relative);
            let Ok(raw) = std::fs::read(&path) else {
                // Published crate archives carry `tests/` but not `docs/`.
                continue;
            };
            let json = crate::parser::prepass::gzip::gunzip(&raw)
                .unwrap_or_else(|error| panic!("{relative}: {error}"));
            let corpus: serde_json::Value =
                serde_json::from_slice(&json).unwrap_or_else(|error| panic!("{relative}: {error}"));
            let cases = corpus["cases"].as_array().expect("cases array");
            assert_eq!(cases.len(), expected_cases, "{relative}: case count");
            for case in cases {
                let name = case["name"].as_str().expect("case name");
                let input = case["input"].as_str().expect("case input");
                check_variants(input, &format!("{relative}/{name}"));
            }
        }
    }
}
