use crate::allocator::{Allocator, Vec};
use crate::ast::{MdxJsxAttributeEntry, MdxJsxAttributeValue, Node, Span};
use memchr::memchr;

pub(super) struct TableCellContent<'a> {
    pub content: &'a str,
    pub source_map: Option<TableCellSourceMap<'a>>,
}

const SOURCE_MAP_BLOCK_BYTES: usize = 64;

#[derive(Clone, Copy)]
struct SourceMapBlock {
    bits: u64,
    prefix: u32,
}

/// Compact rank index for the bytes removed from a table cell. Each block
/// keeps one bit per generated byte and the number of removed bytes before
/// that block, making boundary remapping constant time after a clamp.
pub(super) struct TableCellSourceMap<'a> {
    blocks: Vec<'a, SourceMapBlock>,
    generated_len: u32,
    removed_total: u32,
}

impl<'a> TableCellSourceMap<'a> {
    fn new(allocator: &'a Allocator) -> Self {
        Self {
            blocks: allocator.new_vec(),
            generated_len: 0,
            removed_total: 0,
        }
    }

    fn record_removed(&mut self, generated_position: usize) {
        let block_index = generated_position / SOURCE_MAP_BLOCK_BYTES;
        while self.blocks.len() <= block_index {
            self.blocks.push(SourceMapBlock {
                bits: 0,
                prefix: self.removed_total,
            });
        }
        self.blocks[block_index].bits |= 1u64 << (generated_position % SOURCE_MAP_BLOCK_BYTES);
        self.removed_total += 1;
    }

    fn finish(&mut self, generated_len: usize) {
        self.generated_len = generated_len as u32;
    }

    fn boundary_offset(&self, index: usize) -> u32 {
        // The dense map historically clamped spans beyond the generated
        // source to its final source boundary. Preserve that behavior before
        // looking up the rank bitset.
        let bounded = index.min(self.generated_len as usize);
        let block_index = bounded / SOURCE_MAP_BLOCK_BYTES;
        let within_block = bounded % SOURCE_MAP_BLOCK_BYTES;
        let Some(block) = self.blocks.get(block_index) else {
            return bounded as u32 + self.removed_total;
        };
        let mask = if within_block == 0 {
            0
        } else {
            (1u64 << within_block) - 1
        };
        bounded as u32 + block.prefix + (block.bits & mask).count_ones()
    }
}

/// Removes the table-level escape from pipes before inline parsing.
///
/// GFM treats `\|` as a literal pipe even inside code spans. Normal inline
/// parsing already handles the escape in prose, but code spans preserve
/// backslashes, so the table parser must consume it first.
pub(super) fn unescape_table_pipes<'a>(
    allocator: &'a Allocator,
    content: &'a str,
) -> TableCellContent<'a> {
    let bytes = content.as_bytes();
    // Most cells contain no pipe at all. Search only actual pipe positions
    // instead of examining every byte, then reuse the first escaped match
    // when constructing the remapped source below.
    let Some(first_pipe) = escaped_pipe_scan_start(bytes) else {
        return TableCellContent {
            content,
            source_map: None,
        };
    };

    let mut unescaped = crate::allocator::String::with_capacity_in(content.len(), allocator.bump());
    let mut source_map = TableCellSourceMap::new(allocator);
    let mut copied_through = 0;
    let mut search_start = first_pipe;
    while let Some(relative) = memchr(b'|', &bytes[search_start..]) {
        let pipe = search_start + relative;
        if is_escaped_table_pipe(bytes, pipe) {
            push_unescaped_table_cell_slice(content, copied_through, pipe - 1, &mut unescaped);
            source_map.record_removed(unescaped.len());
            unescaped.push('|');
            copied_through = pipe + 1;
        }
        search_start = pipe + 1;
    }
    push_unescaped_table_cell_slice(content, copied_through, content.len(), &mut unescaped);
    source_map.finish(unescaped.len());
    TableCellContent {
        content: unescaped.into_bump_str(),
        source_map: Some(source_map),
    }
}

#[inline]
fn escaped_pipe_scan_start(bytes: &[u8]) -> Option<usize> {
    // Vector dispatch costs more than the scan for short labels. Keep the
    // scalar path there; long prose cells benefit from skipping whole runs.
    if bytes.len() < 64 {
        return bytes
            .iter()
            .enumerate()
            .any(|(index, &byte)| byte == b'|' && is_escaped_table_pipe(bytes, index))
            .then_some(0);
    }
    memchr::memchr_iter(b'|', bytes).find(|&index| is_escaped_table_pipe(bytes, index))
}

fn push_unescaped_table_cell_slice(
    source: &str,
    start: usize,
    end: usize,
    unescaped: &mut crate::allocator::String<'_>,
) {
    if start < end {
        unescaped.push_str(&source[start..end]);
    }
}

pub(super) fn remap_table_cell_inline_spans(
    node: &mut Node<'_>,
    source_offset: u32,
    source_map: &TableCellSourceMap<'_>,
) {
    match node {
        Node::Text(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::Emphasis(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Strong(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::InlineCode(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::InlineMath(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::Break(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::Link(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Image(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::Highlight(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Delete(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Superscript(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Subscript(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::FootnoteReference(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::Html(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::MdxJsxTextElement(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for attribute in &mut node.attributes {
                remap_table_cell_mdx_attribute_entry(attribute, source_offset, source_map);
            }
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::MdxTextExpression(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
        }
        Node::FootnoteDefinition(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Paragraph(node) => {
            remap_table_cell_span(&mut node.span, source_offset, source_map);
            for child in &mut node.children {
                remap_table_cell_inline_spans(child, source_offset, source_map);
            }
        }
        Node::Heading(_)
        | Node::ThematicBreak(_)
        | Node::BlockQuote(_)
        | Node::List(_)
        | Node::ListItem(_)
        | Node::CodeBlock(_)
        | Node::MathBlock(_)
        | Node::Table(_)
        | Node::DefinitionList(_)
        | Node::DefinitionListTerm(_)
        | Node::DefinitionListDefinition(_)
        | Node::Definition(_)
        | Node::MdxJsxFlowElement(_)
        | Node::MdxjsEsm(_)
        | Node::MdxFlowExpression(_) => {}
    }
}

fn remap_table_cell_mdx_attribute_entry(
    entry: &mut MdxJsxAttributeEntry<'_>,
    source_offset: u32,
    source_map: &TableCellSourceMap<'_>,
) {
    match entry {
        MdxJsxAttributeEntry::Attribute(attribute) => {
            remap_table_cell_span(&mut attribute.span, source_offset, source_map);
            if let Some(MdxJsxAttributeValue::Expression(expr)) = &mut attribute.value {
                remap_table_cell_span(&mut expr.span, source_offset, source_map);
            }
        }
        MdxJsxAttributeEntry::Expression(expr) => {
            remap_table_cell_span(&mut expr.span, source_offset, source_map);
        }
    }
}

fn remap_table_cell_span(span: &mut Span, source_offset: u32, source_map: &TableCellSourceMap<'_>) {
    span.start = source_offset + source_map.boundary_offset(span.start as usize);
    span.end = source_offset + source_map.boundary_offset(span.end as usize);
}

pub(super) fn is_escaped_table_pipe(bytes: &[u8], pipe: usize) -> bool {
    bytes[..pipe]
        .iter()
        .rev()
        .take_while(|&&byte| byte == b'\\')
        .count()
        % 2
        == 1
}

#[cfg(test)]
mod tests;
