#!/usr/bin/env python3
"""Per-case markdown tables for every run of the round: tables.py [out-dir]

Reads results/ of the report this harness belongs to and writes TABLES.md (the Apple Silicon runs)
and X86-TABLES.md (the x86-64 CI runs, one column per host) next to it by default.
Case metadata (category, profile, bytes) comes from results/cases.json, which was taken from the
paired corpus (make_corpus.py --include-scanner-diagnostics; its SHA-256 is in every run.json).
"""
import gzip
import json
import re
import sys
from pathlib import Path

REPORT = Path(__file__).resolve().parent.parent
OUT = Path(sys.argv[1]) if len(sys.argv) > 1 else REPORT
MODES = ("fresh", "reuse", "parse", "render")
RUNS = [
    ("aa6-screen", "A/A control, screen, `060b02d2` against itself"),
    ("tagdispatch-broad", "`tagdispatch` #418 tag filter per-initial candidate sets, broad, base `060b02d2`"),
    ("aa6-recheck6", "A/A control, recheck of #418's five documents"),
    ("tagdispatch-recheck6", "`tagdispatch` #418, recheck of five documents"),
    ("headingid-screen", "`headingid` #422 heading ids in reusable claim storage, screen, base `060b02d2`"),
    ("headingid-broad", "`headingid` #422, broad"),
    ("aa6-recheck422", "A/A control, recheck of #422's six documents"),
    ("headingid-recheck422", "`headingid` #422, recheck of six documents"),
    ("tables2-screen", "`tables2` #424 NEON table pipe cursor, second iteration, screen, base `060b02d2`"),
    ("tables2-broad", "`tables2` #424, broad"),
    ("aa6-recheck424", "A/A control, recheck of #424's seven cases"),
    ("tables2-recheck424", "`tables2` #424, recheck of seven cases"),
    ("lists2-screen", "`lists2` #425 container line facts, second iteration, screen, base `9e741a37`"),
    ("lists2-broad", "`lists2` #425, broad"),
    ("autoidx-screen", "`autoidx` #427 v1 `4fbf1b8e`, autolink triggers from the root scan, screen, base `9e741a37`"),
    ("autoidx-broad", "`autoidx` #427 v1, broad"),
    ("autoidx2-screen", "`autoidx2` #427 v2 `cb73e496`, lazy per-block trigger record, screen, base `9e741a37`"),
    ("autoidx2-broad", "`autoidx2` #427 v2, broad"),
    ("arm426-broad", "`arm426` #426 `b64cc1e6` on aarch64, broad, base `af65cb43`"),
]
X86 = [
    ("aa", "A/A control, #419's head `a4d2fd0a` against itself"),
    ("414", "#414 ASCII-only block trimming `7eda5a4b`, base `aceafd32`"),
    ("426", "#426 first commit `09538a76`, dispatch inlined, base `af65cb43`"),
    ("426b", "#426 revision `b64cc1e6`, dispatch out of line, base `af65cb43`"),
    ("428", "#428 first commit `bdde4db0`, AVX2 at every size, base `05a55a01`"),
    ("428b", "#428 revision `2bf6ba56`, run 1, base `05a55a01`"),
    ("428c", "#428 revision `2bf6ba56`, run 2, base `05a55a01`"),
    ("430", "#430 `5782b91c` inlined SSE2 escape classifiers, base `f8fff4c9`"),
    ("431", "#431 first commit `273b6bf6`, whole scan out of line, base `dfcfe983`"),
    ("431b", "#431 revision `d6e0bad3`, inline 16-byte probe, base `dfcfe983`"),
    ("431inl", "#431 comparison `78429a94`, fully inline, base `dfcfe983`"),
    ("431pl", "#431 placebo `41f4e99e`, base `dfcfe983`"),
    ("total", "cumulative `05a55a01` (2.1.1) against `c6a29e34` (#426 + #430 + #431)"),
]
cases = json.loads((REPORT / "results" / "cases.json").read_text())["cases"]


def median(values):
    ordered = sorted(values)
    middle = len(ordered) // 2
    return ordered[middle] if len(ordered) % 2 else (ordered[middle - 1] + ordered[middle]) / 2


def anchor(heading):
    return re.sub(r"[^a-z0-9 -]", "", heading.lower()).replace(" ", "-")


# Apple Silicon.
lines = ["# Per-case tables, Apple Silicon", "",
         "Ratios are baseline time over candidate time (median of the paired windows); higher is faster.",
         "`Rounds` lists the per-round medians. Baseline time is the median nanoseconds per document.",
         "The x86-64 CI runs are in [X86-TABLES.md](X86-TABLES.md). Generated by `harness/tables.py` from `results/`.", "",
         "Runs:", ""]
lines += [f"- [{heading}](#{anchor(heading)})" for _, heading in RUNS] + [""]
rows_written = 0
for name, heading in RUNS:
    rows = json.loads((REPORT / "results" / name / "summary.json").read_text())
    lines += [f"## {heading}", ""]
    for mode in MODES:
        selected = sorted((r for r in rows if r["mode"] == mode), key=lambda r: r["baseline_over_candidate_median"])
        lines += [f"### {mode}", "",
                  "| Case | Category | Profile | Bytes | Ratio | Min | Max | Rounds | Baseline ns/doc |",
                  "| --- | --- | --- | ---: | ---: | ---: | ---: | --- | ---: |"]
        for r in selected:
            c = cases[r["case"]]
            lines.append(f"| `{r['case']}` | {c['category']} | {c['profile']} | {c['byte_count']} | "
                         f"{r['baseline_over_candidate_median']:.3f} | {r['baseline_over_candidate_min']:.3f} | "
                         f"{r['baseline_over_candidate_max']:.3f} | {' / '.join(f'{x:.3f}' for x in r['round_medians'])} | "
                         f"{r['baseline_ns_per_document']:,.0f} |")
            rows_written += 1
        lines.append("")
(OUT / "TABLES.md").write_text("\n".join(lines))
print("wrote", OUT / "TABLES.md", rows_written, "rows")

# x86-64.
lines = ["# Per-case tables, x86-64 CI", "",
         "Ratios are baseline time over candidate time (median of the paired windows) on each of the three hosts of a "
         "run of the `x86-64 paired benchmark` workflow; higher is faster. Rows are sorted by the median over the "
         "hosts. `Baseline ns/doc` is the median of the hosts' baseline times. Generated by `harness/tables.py` from "
         "`results/x86/`.", "",
         "Runs:", ""]
lines += [f"- [`{name}`: {heading}](#{anchor(f'{name}: {heading}')})" for name, heading in X86] + [""]
rows_written = 0
for name, heading in X86:
    hosts = []
    for directory in sorted((REPORT / "results" / "x86" / name).glob("host-*")):
        model = re.search(r"Model name:\s+(.*)", (directory / "host.txt").read_text()).group(1).strip()
        model = re.sub(r"\s+", " ", re.sub(r"\(R\)|CPU @ [\d.]+GHz|\d+-Core Processor", "", model)).strip()
        rows = json.loads(gzip.decompress((directory / "summary.json.gz").read_bytes()))
        hosts.append((directory.name, model, {(r["mode"], r["case"]): r for r in rows}))
    lines += [f"## `{name}`: {heading}", "",
              "Hosts: " + "; ".join(f"{h} {model}" for h, model, _ in hosts) + ".", ""]
    for mode in MODES:
        names = sorted({case for (m, case) in hosts[0][2] if m == mode},
                       key=lambda c: median([h[2][mode, c]["baseline_over_candidate_median"] for h in hosts]))
        lines += [f"### {mode}", "",
                  "| Case | Category | Profile | Bytes | " + " | ".join(h for h, _, _ in hosts) + " | Median | Baseline ns/doc |",
                  "| --- | --- | --- | ---: | " + " | ".join("---:" for _ in hosts) + " | ---: | ---: |"]
        for case in names:
            c = cases[case]
            ratios = [h[2][mode, case]["baseline_over_candidate_median"] for h in hosts]
            base_ns = median([h[2][mode, case]["baseline_ns_per_document"] for h in hosts])
            lines.append(f"| `{case}` | {c['category']} | {c['profile']} | {c['byte_count']} | "
                         + " | ".join(f"{x:.3f}" for x in ratios) + f" | {median(ratios):.3f} | {base_ns:,.0f} |")
            rows_written += 1
        lines.append("")
(OUT / "X86-TABLES.md").write_text("\n".join(lines))
print("wrote", OUT / "X86-TABLES.md", rows_written, "rows")
