[package]
name = "ferromark_allocator"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/ferromark_allocator"
readme = "README.md"
description = "Arena allocator for Ferromark based on bumpalo"

[lints]
workspace = true

[dependencies]
bumpalo = { workspace = true, features = ["collections", "boxed"] }
