//! CommonMark U+0000 replacement before any syntax or reference parsing.
use ferromark_allocator::{Allocator, Vec};
use ferromark_ast::Span;

use super::spans::SpanMap;

/// One generated byte offset per replacement, not one entry per source byte.
/// Only the root parser owns this map; nested parsers already see normalized
/// source and remap their stripped-source spans before this final mapping.
pub(super) struct NulSourceMap<'a> {
    replacements: Vec<'a, u32>,
}

pub(super) fn normalize<'a>(
    allocator: &'a Allocator,
    source: &'a str,
) -> (&'a str, Option<&'a NulSourceMap<'a>>) {
    let Some(first) = memchr::memchr(0, source.as_bytes()) else {
        // Keep ordinary Markdown borrowed, with no map or string allocation.
        return (source, None);
    };
    let mut normalized = allocator.new_string();
    normalized.reserve(source.len() + 2);
    normalized.push_str(&source[..first]);
    let mut replacements = allocator.new_vec();
    let mut start = first;
    for relative in memchr::memchr_iter(0, &source.as_bytes()[first..]) {
        let offset = first + relative;
        normalized.push_str(&source[start..offset]);
        replacements.push(normalized.len() as u32);
        normalized.push('\u{fffd}');
        start = offset + 1;
    }
    normalized.push_str(&source[start..]);
    let map = allocator.alloc(NulSourceMap { replacements });
    (normalized.into_bump_str(), Some(map))
}

impl NulSourceMap<'_> {
    fn boundary(&self, offset: u32) -> u32 {
        let count = self.replacements.partition_point(|&start| start + 3 <= offset);
        // AST boundaries normally cannot split U+FFFD. Clamp defensively if an
        // error points inside it, so returned offsets remain source boundaries.
        let offset =
            self.replacements.get(count).copied().filter(|&start| start < offset).unwrap_or(offset);
        offset - 2 * count as u32
    }
}

impl SpanMap for NulSourceMap<'_> {
    fn map_span(&self, span: Span) -> Span {
        Span::new(self.boundary(span.start), self.boundary(span.end))
    }
}
