[package]
name = "ferromark-node"
version = "0.7.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
publish = false
build = "build.rs"

[lib]
crate-type = ["cdylib"]
doctest = false
test = false

[features]
panic-test = []

[dependencies]
ferromark = { path = "../.." }
napi = { version = "=3.11.0", default-features = false, features = ["dyn-symbols", "napi8"] }
napi-derive = "=3.6.0"

[build-dependencies]
napi-build = "=2.3.2"
