/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Options {
  renderPolicy?: string
  allowHtml?: boolean
  allowLinkRefs?: boolean
  tables?: boolean
  mergedTableCells?: boolean
  tableColumnWidths?: boolean
  strikethrough?: boolean
  highlight?: boolean
  superscript?: boolean
  subscript?: boolean
  taskLists?: boolean
  autolinkLiterals?: boolean
  disallowedRawHtml?: boolean
  footnotes?: boolean
  inlineFootnotes?: boolean
  frontMatter?: boolean
  headingIds?: boolean
  math?: boolean
  callouts?: boolean
  definitionLists?: boolean
  lineComments?: boolean
  indentedCodeBlocks?: boolean
}

export declare function toHtml(markdown: string, options?: Options | undefined | null): string

export declare function toHtmlWithRenderer(markdown: string, options: Options | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null) => string | null): string
