/* auto-generated by NAPI-RS */
/* eslint-disable */
/** One document heading, in source order. */
export interface Heading {
  /** Heading level, 1-6. */
  level: number
  /** The generated slug; present when the headingIds option is enabled. */
  id?: string
  /** Plain heading text with inline markup and HTML tags removed. */
  text: string
}

export interface Options {
  renderPolicy?: string
  allowHtml?: boolean
  allowLinkRefs?: boolean
  tables?: boolean
  mergedTableCells?: boolean
  tableColumnWidths?: boolean
  strikethrough?: boolean
  highlight?: boolean
  superscript?: boolean
  subscript?: boolean
  taskLists?: boolean
  autolinkLiterals?: boolean
  disallowedRawHtml?: boolean
  footnotes?: boolean
  inlineFootnotes?: boolean
  frontMatter?: boolean
  headingIds?: boolean
  math?: boolean
  callouts?: boolean
  definitionLists?: boolean
  lineComments?: boolean
  indentedCodeBlocks?: boolean
  linkBasePath?: string
}

export declare function toHtml(markdown: string, options?: Options | undefined | null): string

export declare function toHtmlWithRenderer(markdown: string, options: Options | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): string

/** Render Markdown and return HTML together with headings and front matter. */
export declare function transform(markdown: string, options?: Options | undefined | null): TransformResult

/** Result of `transform`: HTML plus document metadata. */
export interface TransformResult {
  html: string
  /** Document headings for table-of-contents rendering. */
  headings: Array<Heading>
  /**
   * Raw front matter text (between the delimiters); present when the
   * frontMatter option is enabled and the document starts with a block.
   */
  frontMatter?: string
}

/**
 * `transform` with an opt-in fenced-code renderer callback.
 *
 * The callback receives `(code, language, meta)` and must return trusted,
 * fully escaped HTML — or null/undefined to fall back to the default
 * escaped `<pre><code>` output.
 */
export declare function transformWithRenderer(markdown: string, options: Options | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): TransformResult
