/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Owns a Ferriki highlighter, asset catalogs, and theme registrations across documents. */
export declare class JsxCompiler {
  constructor(settings: string)
  /** Compiles source and reuses the loaded native grammars and themes. */
  compile(markdown: string | Uint8Array, options?: Options | undefined | null, jsxOptions?: JsxOptions | undefined | null, renderCode?: (code: string, language?: string | null, meta?: string | null) => string | null | undefined): JsxResult
  /** Compiles source to an MDX module; the public facade selects this entry. */
  compileModule(markdown: string | Uint8Array, options?: Options | undefined | null, jsxOptions?: JsxOptions | undefined | null, renderCode?: (code: string, language?: string | null, meta?: string | null) => string | null | undefined): JsxModuleResult
}

/** Reuses arena storage and HTML buffers; documents never outlive a call. */
export declare class Renderer {
  constructor(options?: Options | undefined | null)
  /** Internal to the `ferromark` facade: the constructor with packed options. */
  static withPackedOptions(set: number, on: number, headingOffset?: number | undefined | null, headingIdPrefix?: string | undefined | null, linkBasePath?: string | undefined | null, typography?: TypographyConfig | undefined | null, passes?: Array<NativePassConfig> | undefined | null): Renderer
  toHtml(markdown: string | Uint8Array): string
  toHtmlBuffer(markdown: string | Uint8Array): Buffer
}

/** Internal entry: the public facade validates and separates its option keys. */
export declare function compileJsx(markdown: string | Uint8Array, options?: Options | undefined | null, jsxOptions?: JsxOptions | undefined | null, renderCode?: (code: string, language?: string | null, meta?: string | null) => string | null | undefined): JsxResult

/** Internal entry for `output: "module"`; the public facade selects it. */
export declare function compileJsxModule(markdown: string | Uint8Array, options?: Options | undefined | null, jsxOptions?: JsxOptions | undefined | null, renderCode?: (code: string, language?: string | null, meta?: string | null) => string | null | undefined): JsxModuleResult

export interface Heading {
  level: number
  id?: string
  text: string
}

export interface JsxCodeBlock {
  code: string
  language?: string
  meta?: string
}

export interface JsxHeading {
  level: number
  id?: string
  text: string
  start: number
  end: number
}

/** A version 3 source map for module code. */
export interface JsxModuleMap {
  version: number
  sources: Array<string>
  sourcesContent: Array<string>
  names: Array<string>
  mappings: string
}

export interface JsxModuleResult {
  code: string
  map: JsxModuleMap
  exports: Array<string>
  bindings: Array<string>
  codeBlocks: Array<JsxCodeBlock>
  headings: Array<JsxHeading>
  frontMatter?: string
  frontMatterSpan?: SourceRange
  frontMatterKind?: string
  omittedTitleHeadingSpan?: SourceRange
}

export interface JsxModuleSource {
  value: string
  start: number
  end: number
}

export interface JsxOptions {
  format?: string
  componentPrefix?: string
  calloutComponents?: Record<string, string>
  codeComponents?: Record<string, string>
  codeBlockComponent?: string
  omitTitleHeading?: string
  /** Module output only: module that exports `useMDXComponents`. */
  providerImportSource?: string
  /** Module output only: source file name for the source map. */
  filename?: string
  /** Module output only: export `MDXContent` as the default export. */
  defaultExport?: boolean
  /** Module output only: names the caller declares in code it adds. */
  reservedBindings?: Array<string>
}

export interface JsxResult {
  body: string
  esm: Array<JsxModuleSource>
  components: Array<string>
  elements: Array<string>
  codeBlocks: Array<JsxCodeBlock>
  headings: Array<JsxHeading>
  frontMatter?: string
  frontMatterSpan?: SourceRange
  frontMatterKind?: string
  omittedTitleHeadingSpan?: SourceRange
  mappings: Array<JsxSourceMapping>
}

export interface JsxSourceMapping {
  generatedLine: number
  generatedColumn: number
  sourceLine: number
  sourceColumn: number
}

export interface NativePassConfig {
  kind?: string
  language?: string
  dashes?: boolean
  ellipses?: boolean
  repository?: string
}

export interface Options {
  renderPolicy?: string
  allowHtml?: boolean
  tables?: boolean
  mergedTableCells?: boolean
  tableColgroup?: boolean
  tableColumnNames?: boolean
  tableAttributes?: boolean
  strikethrough?: boolean
  superscript?: boolean
  subscript?: boolean
  taskLists?: boolean
  autolinkLiterals?: boolean
  disallowedRawHtml?: boolean
  footnotes?: boolean
  highlight?: boolean
  inlineFootnotes?: boolean
  allowLinkRefs?: boolean
  frontMatter?: boolean
  headingIds?: boolean
  headingOffset?: number
  headingIdPrefix?: string
  headingAttributes?: boolean
  math?: boolean
  callouts?: boolean
  definitionLists?: boolean
  lineComments?: boolean
  cjkEmphasis?: boolean
  mdx?: boolean
  imageAttributes?: boolean
  imageCaptions?: boolean
  extendedAttributes?: boolean
  bracketedSpans?: boolean
  linkBasePath?: string
  typography?: TypographyConfig
  passes?: Array<NativePassConfig>
  blockquoteAttributions?: boolean
  insertions?: boolean
  guillemetDigraphs?: boolean
  autoAbbreviations?: boolean
  abbreviations?: Record<string, string | undefined | null>
  preset?: string
}

export interface SourceRange {
  start: number
  end: number
}

export declare function toHtml(markdown: string | Uint8Array, options?: Options | undefined | null): string

export declare function toHtmlBuffer(markdown: string | Uint8Array, options?: Options | undefined | null): Buffer

/** Internal to the `ferromark` facade: `toHtmlBuffer` with packed options. */
export declare function toHtmlBufferPacked(markdown: string | Uint8Array, set: number, on: number, headingOffset?: number | undefined | null, headingIdPrefix?: string | undefined | null, linkBasePath?: string | undefined | null, typography?: TypographyConfig | undefined | null, passes?: Array<NativePassConfig> | undefined | null): Buffer

/** Internal to the `ferromark` facade: `toHtml` with packed options. */
export declare function toHtmlPacked(markdown: string | Uint8Array, set: number, on: number, headingOffset?: number | undefined | null, headingIdPrefix?: string | undefined | null, linkBasePath?: string | undefined | null, typography?: TypographyConfig | undefined | null, passes?: Array<NativePassConfig> | undefined | null): string

export declare function toHtmlWithRenderer(markdown: string | Uint8Array, options: Options | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): string

/**
 * Internal to the `ferromark` facade: `toHtmlWithRenderer` with packed
 * options.
 */
export declare function toHtmlWithRendererPacked(markdown: string | Uint8Array, set: number, on: number, headingOffset: number | undefined | null, headingIdPrefix: string | undefined | null, linkBasePath: string | undefined | null, typography: TypographyConfig | undefined | null, passes: Array<NativePassConfig> | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): string

export declare function transform(markdown: string | Uint8Array, options?: Options | undefined | null): TransformResult

/** Internal to the `ferromark` facade: `transform` with packed options. */
export declare function transformPacked(markdown: string | Uint8Array, set: number, on: number, headingOffset?: number | undefined | null, headingIdPrefix?: string | undefined | null, linkBasePath?: string | undefined | null, typography?: TypographyConfig | undefined | null, passes?: Array<NativePassConfig> | undefined | null): TransformResult

export interface TransformResult {
  html: string
  headings: Array<Heading>
  frontMatter?: string
}

export declare function transformWithRenderer(markdown: string | Uint8Array, options: Options | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): TransformResult

/**
 * Internal to the `ferromark` facade: `transformWithRenderer` with packed
 * options.
 */
export declare function transformWithRendererPacked(markdown: string | Uint8Array, set: number, on: number, headingOffset: number | undefined | null, headingIdPrefix: string | undefined | null, linkBasePath: string | undefined | null, typography: TypographyConfig | undefined | null, passes: Array<NativePassConfig> | undefined | null, renderer: (arg0: string, arg1?: string | undefined | null, arg2?: string | undefined | null) => string | null): TransformResult

export interface TypographyConfig {
  language?: string
  dashes?: boolean
  ellipses?: boolean
}
