name: Quoted full SHA

on: workflow_dispatch

jobs:
  pinned:
    runs-on: ubuntu-latest
    steps:
      - { uses: "actions/checkout@0123456789abcdef0123456789abcdef01234567" }
      - { uses: 'actions/cache@fedcba9876543210fedcba9876543210fedcba98' }
