#!/usr/bin/env python3
"""Assemble the issue-320 report directory: make_report320.py <candidate-name> <out-dir>

Copies the paired-measurement results (A/A control, marker-free reproduction, issue documents,
57 broad, 45 diagnostics) with samples gzipped, the three diagnostic corpus variants, the harness
scripts, writes TABLES.md and a machine-generated numbers section (NUMBERS.md) that the README quotes,
and a SHA256SUMS over everything.
"""
import gzip, hashlib, json, os, shutil, subprocess, sys
from pathlib import Path
from statistics import geometric_mean

S = Path(__file__).resolve().parent
cand, out = sys.argv[1], Path(sys.argv[2])
out.mkdir(parents=True, exist_ok=True)
(out / "results").mkdir(exist_ok=True)
(out / "harness").mkdir(exist_ok=True)

runs = {"aa320-load": "aa-control", "aa320-repro": "aa-repro", f"{cand}-issue": "issue-docs",
        f"{cand}-broad": "broad", f"{cand}-diag": "diagnostics"}
for src, dst in runs.items():
    d = out / "results" / dst; d.mkdir(exist_ok=True)
    for name in ("summary.json", "grouped.json", "run.json", "build.json"):
        p = S / "results" / src / name
        if p.exists(): shutil.copy(p, d / name)
    for name in ("samples.json", "arena-capacities.json"):
        p = S / "results" / src / name
        if p.exists():
            with open(p, "rb") as f, gzip.open(d / f"{name}.gz", "wb", compresslevel=9) as g: shutil.copyfileobj(f, g)
for name in ("make_candidate320.sh", "confirm320.sh", "screen320.sh", "percase.py", "tables.py", "make_report320.py"):
    shutil.copy(S / name, out / "harness" / name)

# the three diagnostic variants (every "]:" replaced by "]=")
c = json.load(open(S / "corpus320.json")); docs = c.get("documents") or c.get("cases")
variants = [d for d in docs if d["name"].endswith("-nodef")]
with gzip.open(out / "corpus-variants.json.gz", "wt", compresslevel=9) as g: json.dump({"documents": variants}, g)

def load(n): return {(r["mode"], r["case"]): r for r in json.load(open(S / "results" / n / "summary.json"))}
issue, broad, diag, aa, repro = load(f"{cand}-issue"), load(f"{cand}-broad"), load(f"{cand}-diag"), load("aa320-load"), load("aa320-repro")
grouped = {n: json.load(open(S / "results" / n / "grouped.json")) for n in (f"{cand}-broad", f"{cand}-diag", "aa320-load")}
modes = ("fresh", "reuse", "parse", "render")
L = ["# Numbers (generated by harness/make_report320.py)", ""]
def geo_line(label, g, n):
    v = g["all"]; return f"| {label} | {n} | " + " | ".join(f"{v[m]['geometric_mean']:.3f}× (rounds {', '.join(f'{x:.3f}' for x in v[m]['round_geometric_means'])})" for m in modes) + " |"
L += ["## Geometric means", "", "| Set | N | Fresh | Reuse | Parse | Render |", "| --- | ---: | --- | --- | --- | --- |",
      geo_line("A/A control (same binary twice, 10 documents)", grouped["aa320-load"], 10),
      geo_line("Original broad documents", grouped[f"{cand}-broad"], 57),
      geo_line("Authored diagnostics", grouped[f"{cand}-diag"], 45), ""]
L += ["## Broad categories", "", "| Category | N | Fresh | Reuse | Parse | Render |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
for cat, cv in grouped[f"{cand}-broad"]["categories"].items():
    L.append(f"| {cat} | {cv['fresh']['cases']} | " + " | ".join(f"{cv[m]['geometric_mean']:.3f}×" for m in modes) + " |")
L += ["", "## Above / below 1 (broad)", "", "| Stage | Above | Below | Min | Max |", "| --- | ---: | ---: | ---: | ---: |"]
for m in modes:
    vals = [r["baseline_over_candidate_median"] for (mm, _), r in broad.items() if mm == m]
    L.append(f"| {m} | {sum(v > 1 for v in vals)} | {sum(v < 1 for v in vals)} | {min(vals):.3f} | {max(vals):.3f} |")
L += ["", "## Reproduction on the baseline binary: discovery cost", "",
      "Original document time over the time of the same document with every `]:` replaced by `]=`, both measured in the same A/A run (baseline side).", "",
      "| Document | Fresh | Reuse | Parse | Render |", "| --- | ---: | ---: | ---: | ---: |"]
for doc in ("comment-incident", "rust-book-ch00-00-introduction", "typescript-handbook-advanced-types"):
    cells = []
    for m in modes:
        a, b = repro[(m, doc)], repro[(m, doc + "-nodef")]
        cells.append(f"{a['baseline_ns_per_document'] / b['baseline_ns_per_document']:.3f} ({a['baseline_ns_per_document']/1000:.2f} vs {b['baseline_ns_per_document']/1000:.2f} µs)")
    L.append(f"| `{doc}` | " + " | ".join(cells) + " |")
L += ["", "## Issue documents, candidate against baseline", "", "| Document | Stage | Ratio | Rounds | Baseline µs | Candidate µs | Δ ns |", "| --- | --- | ---: | --- | ---: | ---: | ---: |"]
for (m, c_), r in sorted(issue.items(), key=lambda kv: (kv[0][1], modes.index(kv[0][0]))):
    b = r["baseline_ns_per_document"]; x = r["baseline_over_candidate_median"]
    L.append(f"| `{c_}` | {m} | {x:.3f} | {' / '.join(f'{v:.3f}' for v in r['round_medians'])} | {b/1000:.2f} | {b/x/1000:.2f} | {b/x-b:+.0f} |")
for name, rows in (("broad", broad), ("diagnostics", diag)):
    L += ["", f"## {name}: cases outside 0.97–1.03", "", "| Document | Stage | Ratio | Rounds | Baseline ns |", "| --- | --- | ---: | --- | ---: |"]
    for (m, c_), r in sorted(rows.items(), key=lambda kv: kv[1]["baseline_over_candidate_median"]):
        x = r["baseline_over_candidate_median"]
        if x < 0.97 or x > 1.03:
            L.append(f"| `{c_}` | {m} | {x:.3f} | {' / '.join(f'{v:.3f}' for v in r['round_medians'])} | {r['baseline_ns_per_document']:,.0f} |")
(out / "NUMBERS.md").write_text("\n".join(L) + "\n")
subprocess.run([sys.executable, str(S / "tables.py"), str(S), str(out / "TABLES.md"),
                "Per-case tables — segmented definition pass against main",
                f"{cand}-issue=Issue 320 documents and marker-free variants (9)", f"{cand}-broad=Original broad documents (57)",
                f"{cand}-diag=Authored diagnostics (45)", "aa320-load=A/A control (10)"], check=True)
sums = []
for p in sorted(out.rglob("*")):
    if p.is_file() and p.name != "SHA256SUMS":
        sums.append(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.relative_to(out).as_posix()}")
(out / "SHA256SUMS").write_text("\n".join(sums) + "\n")
print("report assembled in", out, "files:", len(sums))
